### PR TITLE
Feat/ci

### LINKED ISSUE #7: Mise en place CI / Dockerisation

### PR DESCRIPTION
**Pull request by Unknow46**

### CODE REVIEW

**Comment by zaydane-mokni** [comment]
Nothing to preview, i approve

**Review by zaydane-mokni — APPROVED** [review]
Nothing to preview, i approve

**Review by oussamaHJM — COMMENTED** [review]
Done nothing to review

**Comment by oussamaHJM** [comment]
done

**Review by oussamaHJM — APPROVED** [review]
Approuved

**Pull request merged**
